<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <ClassIslandPluginSdkVersion>2.0.0.2</ClassIslandPluginSdkVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClassIsland.PluginSdk" Version="$(ClassIslandPluginSdkVersion)" GeneratePathProperty="true">
            <ExcludeAssets>runtime; native</ExcludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Update="manifest.yml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="README.md">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="LICENSE">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </None>
        <None Update="icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <Target Name="CreateCipxFromPublishOutput"
            AfterTargets="Publish"
            Condition="'$(CreateCipx)'=='true'">
        <PropertyGroup>
            <CipxPackageOutputDirectory>$(MSBuildProjectDirectory)\cipx</CipxPackageOutputDirectory>
            <CipxPackageOutputName>$(MSBuildProjectName).cipx</CipxPackageOutputName>
            <ClassIslandPublishCipxOutputPath>$(CipxPackageOutputDirectory)\$(CipxPackageOutputName)</ClassIslandPublishCipxOutputPath>
        </PropertyGroup>

        <Error Condition="Exists('$(PublishDir)manifest.yml') != 'true'"
               Code="CISDK0001"
               Text="插件清单 manifest.yml 在发布目录中不存在" />
        <MakeDir Directories="$(CipxPackageOutputDirectory)"
                 Condition="Exists('$(CipxPackageOutputDirectory)') != 'true'" />
        <ZipDirectory SourceDirectory="$(PublishDir)"
                      Overwrite="true"
                      DestinationFile="$(ClassIslandPublishCipxOutputPath)" />
        <Delete Files="$(CipxPackageOutputDirectory)\checksums.md"
                Condition="Exists('$(CipxPackageOutputDirectory)\checksums.md')" />
        <Exec Command="$(PowershellBinaryName) -ep bypass -NoLogo -File &quot;$(PkgClassIsland_PluginSdk)\build\net8.0\generate-md5.ps1&quot; &quot;$(CipxPackageOutputDirectory)&quot;"
              Condition="'$(GenerateHashSummary)'=='true'" />
    </Target>

</Project>
